config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'
  get 'pages/about'
  devise_for :users
  resources :plants
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/plant.rb
class Plant < ApplicationRecord
    validates :name, :price, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!, unless: :devise_controller?
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!
  def home
  end

  def about
  end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_plant, only: %i[ show edit update destroy ]

  # GET /plants or /plants.json
  def index
    @plants = Plant.all
  end

  # GET /plants/1 or /plants/1.json
  def show
  end

  # GET /plants/new
  def new
    @plant = Plant.new
  end

  # GET /plants/1/edit
  def edit
  end

  # POST /plants or /plants.json
  def create
    @plant = Plant.new(plant_params)

    respond_to do |format|
      if @plant.save
        format.html { redirect_to plant_url(@plant), notice: "Plant was successfully created." }
        format.json { render :show, status: :created, location: @plant }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @plant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plants/1 or /plants/1.json
  def update
    respond_to do |format|
      if @plant.update(plant_params)
        format.html { redirect_to plant_url(@plant), notice: "Plant was successfully updated." }
        format.json { render :show, status: :ok, location: @plant }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @plant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plants/1 or /plants/1.json
  def destroy
    @plant.destroy

    respond_to do |format|
      format.html { redirect_to plants_url, notice: "Plant was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plant
      @plant = Plant.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def plant_params
      params.require(:plant).permit(:name, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light mb-5">
  <div class="container-fluid">
    <a class="navbar-brand">GreenBaazar</a>   
    <div class="d-flex">
      <% if user_signed_in? %>      
        <span class="mt-2 me-3"><%= current_user.email %></span>      
        <%= button_to "Sign out", destroy_user_session_path, method: :delete,  class: "btn btn-secondary" %>
      <% else %>
        <%= link_to "Sign in", new_user_session_path, class: "btn btn-success" %>
      <% end  %>
    </div>    
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GreenBaazar</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    
    <div class="container">
      <div class="row">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/home.html.erb
<main class="container">
    <div class="card">
        <div class="card-header">    
            <h1>Plant </h1>
        </div>
        <div class="card-body my-5 text-center">
            <h1>Welcome to Home page</h1>
            <% if user_signed_in? %>
                <%= link_to "View plants", plants_path, class: "btn btn-primary" %>
            <% else %>
                <%= link_to "Sign in", new_user_session_path, class: "btn btn-primary" %>
            <% end %>
        </div>
    </div>
</main>

app/views/plants/_form.html.erb
<%= form_with(model: plant) do |form| %>
  <% if plant.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(plant.errors.count, "error") %> prohibited this plant from being saved:</h2>

      <ul>
        <% plant.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group mb-3">
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, class: "form-control form-control-lg" %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :price, style: "display: block" %>
    <%= form.number_field :price, class: "form-control form-control-lg" %>
  </div>

  <div class="form-group mt-3">
    <%= form.submit class: "btn btn-primary btn-lg" %>
    <%= link_to "Back to plants", plants_path, class:"btn btn-outline-primary btn-lg" %>
  </div>
<% end %>

app/views/plants/_plant.html.erb
<div id="<%= dom_id plant %>">
  <p>
    <strong>Name:</strong>
    <%= plant.name %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= plant.price %>
  </p>

</div>

app/views/plants/edit.html.erb
<div class="col-lg-12 mx-auto">
  <div class="card shadow">
    <div class="card-header">
      <h1 class="card-title"><h1>Editing plant</h1></h1>
    </div>
    <div class="card-body">
      <%= render "form", plant: @plant %>
    </div>
  </div>
</div>

app/views/plants/index.html.erb
<p style="color: green"><%= notice %></p>
<div class="col-lg-12 mx-auto">
  <h1>Plants</h1>
  <div class="d-flex justify-content-end">
    <%= link_to "New plant", new_plant_path, class: "btn btn-primary btn-lg mb-3" %>
  </div>
  <% if @plants.present? %>
    <div id="plants">
      <% @plants.each do |plant| %>
        <div class="card shadow mb-3">
          <div class="card-body">
            <%= render plant %>
            <div class="d-flex">
              <%= link_to "Show this plant", plant, class: "btn btn-primary me-3" %>
              <%= button_to "Destroy this plant", plant, method: :delete, class: "btn btn-danger" %>
            </div>
          </div>
        </div>      
      <% end %>
    </div>
  <% else %>
    <div class="card shadow mb-3">
      <div class="card-body">
        <span>There is no data, create new data.</span>
      </div>
    </div> 
  <% end  %>
</div>

app/views/plants/new.html.erb
<div class="col-lg-12 mx-auto">
  <div class="card shadow">
    <div class="card-header">
      <h1 class="card-title"><h1>New plant</h1></h1>
    </div>
    <div class="card-body">
      <%= render "form", plant: @plant %>
    </div>
  </div>
</div>

app/views/plants/show.html.erb
<p style="color: green"><%= notice %></p>
<div class="col-lg-12">
  <div class="card shadow">
    <div class="card-header">
      <h1 class="card-title"><h1>Plant Details</h1></h1>
    </div>
    <div class="card-body">
      <%= render @plant %>
    </div>
    <div class="card-footer">
      <div class="d-flex justify-content-between">
        <div>
          <%= button_to "Destroy this plant", @plant, method: :delete, class: "btn btn-danger" %>
        </div>
        <div>
          <%= link_to "Back to plants", plants_path, class: "btn btn-outline-primary" %>
          <%= link_to "Edit this plant", edit_plant_path(@plant), class: "btn btn-warning" %> 
        </div>
      </div>
    </div>
  </div>
</div>